### ISSUE TITLE
Future of this project

### ISSUE THREAD

**Issue by feathecutie** [AgathaSorceress/json2kdl#1]
Hey, as you might have seen in the [nixpkgs issue regarding this](https://github.com/NixOS/nixpkgs/issues/198655), I have recently forked this repo in order to implement `pkgs.formats.kdl` in nixpkgs. That implemention (https://github.com/feathecutie/nixpkgs/tree/formats-kdl) is basically ready to be upstreamed now, but would also requiring packaging some version of this project in nixpkgs.

Are you interested in me contributing my changes back into this repo, in order to make this repo the main codebase that gets packaged? Otherwise (if you're not interested in continuing to maintain this), I would simply upstream my fork of this repo instead.

**Comment by AgathaSorceress** [comment]
I would be happy to merge your changes and continue maintaining them :)

**Comment by feathecutie** [comment]
Sure! I'll open a PR then

**Comment by feathecutie** [comment]
Btw, I do already have an [open PR in nixpkgs](https://github.com/NixOS/nixpkgs/pull/295211) for this now, with myself added as a maintainer for this package. I would simply change the `src` of the package to your repo then, but if you prefer to be the nixpkgs maintainer of this, you could also upstream this package yourself (I don't think I'd be allowed to add you as a maintainer in my PR at least), and I would just indicate that my PR depends on yours.

**Comment by eclairevoyant** [comment]
> I don't think I'd be allowed to add you as a maintainer in my PR at least

That's fine as long as they've confirmed agreement. And "maintainer" in nixpkgs mostly means getting pings about issues/PRs; anyone can submit a PR to update the package.

**Comment by feathecutie** [comment]
In that case, it would probably make sense to just do everything in one PR.

@AgathaSorceress: If you'd like to, I could add you to the maintainers list of this package in my PR. However, you also don't seem to be in `maintainers-list.nix` yet, so this would require me adding you there too.
This would require you somehow sending me your preferred entry for the maintainers list, which would be doable but it might make more sense to just do this yourself in a later PR if that's something you care about, and for me to just merge my PR as is (once you've merged my changes back into this repo).

**Comment by AgathaSorceress** [comment]
I just merged your changes, can also make a release/tag if it would be useful. I think it makes the most sense for you to merge your PR and for me to just add myself as a maintainer later.

**Comment by feathecutie** [comment]
Neat, thanks! A tag is not really necessary I think
